kind: Job
apiVersion: batch/v1
metadata:
  name: check-db-connections
  namespace: prodns
spec:
  template:
    spec:
      containers:
      - name: network-checker
        image: busybox
        command: ["ping", "-c", "5", "redis"]
      restartPolicy: Never

