kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: django-app
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


#######################################################################


kind: Service
apiVersion: v1
metadata:
  name: djnago-app
  namespace: django-app
spec:
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


#################################################################################
