kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql
spec:
  serviceName: mysql
  replicas: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql    
      resources:
        requests:
          memory: "250Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "1000m"

volumeClaimTemplates:
- metadata:
    name: mysql-storage
  spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi

##########################################################################################

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql
spec:
  serviceName: mysql
  replicas: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        volumeMounts:
        - name: mysql-Storage
          mountPath: /var/lib/mysql
      resources:
        requests: 
          memory: "250Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "1000m"

volumeClaimTemplates:
- metadata:
    name: mysql-storage
  spec:
    accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

########################################################################################################################


kind: statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: mysql
  replicas: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123465
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      resources:
        requests:
          memory: "250Mi"
          cpu: "128m"
        limits:
          memory: "500Mi"
          cpu: "256m"

  volumeClaimTemplates:
  - metadata:
    name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      
#####################################################################################################################

kind: Statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: mysql
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "524Mi"
            cpu: "256m"


  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:    
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi



#################################################################################################################

kind: statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            cpu: "256m"
              

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
          resouces:
            requests:
              storage: 1Gi

#####################################################################################################################





kind: statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: mysql-
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            cpu: "256m"

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec: 
      accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1Gi"

#############################################################################################################################


kind: statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: mysql
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT-PASSWORD
          value: "123456"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            cpu: "256m"
  

  VolumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1Gi"
      
###################################################################################################################

kind: statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  servicename: mysql
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT-PASSWORD
          value: "123456"
        volumePath:
        - name: Mysql-storage
          path: /var/lib/mysql
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "264Mi"
            cpu: "128m"

  VolumeClaimTemplate:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "1Gi"


###################################################################################################################

kind: Statefulset
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql
spec:
  replicas: 3
  selector:
    matchlabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL-ROOT-PASSWORD
          value: "12345678"
        volumePath:
        - name: mysql-storage
          path: /var/lib/mysql
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"

  VolumeClaimTemplate:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
        resources:    
          request:
            storage: "1Gi"


################################################################################################################################################

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-ns
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12346578"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi" 
            cpu: "64m"
          limits:
            memory: "512Mi"
            cpu: "128Mi"


  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec: 
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "1Gi"



#########################################################################################################################

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels: 
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456789"
        - name: MYSQL_USER
          value: ayush
        - name: MYSQL_PASSWORD
          value: 123456
        - name: MYSQL_DATABASE
          value: aman
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "128m"


#########################################################################################################


kind: StatefulSet
apiVersion: v1
metadata:
  name: mysql-service
  namespace: mysql-db
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: mysql-db
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-cont
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: root-password
        ports:
        - containerPorts: 3306
        volumeMounts:
        - name: data-disk
          mountPath: /var/lib/mysql
  VolumeClaimTemplates:
  - metadata:
      name: data-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

